### PR TITLE
Forward PTR record lookup from kubedns to upstream server.

### LINKED ISSUE #198: Reverse IP lookup of external IPs not working with kube-dns upstreamNameservers
**What happened**:

We’re trying to do reverse IP lookups from a GKE container (ex. `dig +short -t PTR x.x.x.x.in-addr.arpa`)  and this doesn’t seem to be working. `kube-dns` is set with `upstreamNameservers` via the `kube-dns` ConfigMap in the `kube-system` namespace.

**What you expected to happen**:

I would expect the reverse IP lookups to be passed along to the specified upstream nameservers similar to regular DNS lookups but it doesn’t seem like this is the case.

From within a running container in k8s:

```
root@debugging-65cb9f5b47-rbf99:/# dig +short -t PTR y.y.y.y.in-addr.arpa
root@debugging-65cb9f5b47-rbf99:/# dig @x.x.x.x +short -t PTR y.y.y.y.in-addr.arpa
hostname.company.net.
```

where `x.x.x.x` is the IP address of one of the `upstreamNameserver`s we set in the `kube-dns` configmap in the `kube-system` namespace (this is on GKE).

### PR DESCRIPTION
**Pull request by grayluck**
Fixes #198

Approach: Let kubedns sync config to skydns nameservers, allowing skydns to do the request forwarding.

### CODE REVIEW

**Comment by MrHohn** [comment]
@grayluck Seems like travis failed on this:
```
--- FAIL: TestConfigSync (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x11963f6]
goroutine 38 [running]:
testing.tRunner.func1(0xc4204651d0)
	/usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0x12e4380, 0x1cb8c40)
	/usr/local/go/src/runtime/panic.go:491 +0x283
k8s.io/dns/pkg/dns.(*KubeDNS).updateConfig(0xc42027f200, 0xc4201a5950)
	/go/src/k8s.io/dns/pkg/dns/dns.go:160 +0x346
k8s.io/dns/pkg/dns.(*KubeDNS).startConfigMapSync(0xc42027f200)
	/go/src/k8s.io/dns/pkg/dns/dns.go:214 +0x20a
k8s.io/dns/pkg/dns.TestConfigSync(0xc4204651d0)
	/go/src/k8s.io/dns/pkg/dns/dns_test.go:683 +0x164
testing.tRunner(0xc4204651d0, 0x14b7ff8)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de
FAIL	k8s.io/dns/pkg/dns	0.125s
```

File: Makefile [hunk 1]
```diff
@@ -27,15 +27,18 @@ BINARIES := \
...
 # You must have a matching Dockerfile.BINARY for each BINARY.
-CONTAINER_BINARIES := \
-    dnsmasq-nanny \
-    kube-dns \
-    sidecar
+# CONTAINER_BINARIES := \
+#     dnsmasq-nanny \
+#     kube-dns \
+#     sidecar
+CONTAINER_BINARIES := kube-dns
```
Comment (bowei) [inline Makefile]: remove?

File: Makefile [hunk 2]
```diff
@@ -27,15 +27,18 @@ BINARIES := \
...
 
 # List of images to build (contained in images/)
 IMAGES := dnsmasq
 # Registry to push to.
-REGISTRY ?= staging-k8s.gcr.io
+# REGISTRY ?= gcr.io
+REGISTRY ?= gcr.io/yankaiz-kube-test
```
Comment (bowei) [inline Makefile]: revert

File: cmd/kube-dns/app/server.go [hunk 3]
```diff
@@ -163,40 +162,6 @@ func setupSignalHandlers() {
 	}()
 }
 
-func validateHostAndPort(hostAndPort string) error {
```
Comment (bowei) [inline cmd/kube-dns/app/server.go]: I think this should just go into config/ package instead of creating a new package `util`

File: pkg/dns/dns.go [hunk 4]
```diff
@@ -57,6 +58,9 @@ type KubeDNS struct {
 	// to get Endpoints and Service objects.
 	kubeClient clientset.Interface
 
+	// skydns points to the skydns server instance for configuration syncing.
+	skydnsConfig *server.Config
```
Comment (bowei) [inline pkg/dns/dns.go]: Let's just make this a Public field and call set directly

`SkyDNSConfig *server.Config`

File: pkg/dns/dns.go [hunk 5]
```diff
@@ -135,6 +139,32 @@ func NewKubeDNS(client clientset.Interface, clusterDomain string, timeout time.D
 	return kd
 }
 
+// BondSkydnsConfig bonds the configuration of skydns for config sync. The
+// function encapsulates skydnsConfig inside KubeDNS struct.
+func (kd *KubeDNS) BondSkydnsConfig(config *server.Config) {
```
Comment (bowei) [inline pkg/dns/dns.go]: delete this...

File: pkg/dns/dns.go [hunk 6]
```diff
@@ -135,6 +139,32 @@ func NewKubeDNS(client clientset.Interface, clusterDomain string, timeout time.D
...
+	kd.skydnsConfig = config
+}
+
+func (kd *KubeDNS) updateConfig(nextConfig *config.Config) {
+	kd.configLock.Lock()
```
Comment (bowei) [inline pkg/dns/dns.go]: `defer kd.configLock.Unlock()`

File: pkg/dns/dns.go [hunk 7]
```diff
@@ -135,6 +139,32 @@ func NewKubeDNS(client clientset.Interface, clusterDomain string, timeout time.D
...
+	kd.config = nextConfig
+
+	if kd.skydnsConfig != nil {
+		var nameservers []string
+		for _, nameserver := range kd.config.UpstreamNameservers {
+			if nameserverIpPort, err := util.ValidateNameServer(nameserver); err != nil {
+				glog.V(1).Infof("Invalid nameserver in configuration %s: %v", nameserver, err)
```
Comment (bowei) [inline pkg/dns/dns.go]: glog.Errorf

File: pkg/dns/dns.go [hunk 8]
```diff
@@ -135,6 +139,32 @@ func NewKubeDNS(client clientset.Interface, clusterDomain string, timeout time.D
...
+			} else {
+				nameservers = append(nameservers, nameserverIpPort)
+			}
+		}
+		kd.skydnsConfig.Nameservers = nameservers
```
Comment (bowei) [inline pkg/dns/dns.go]: Should probably not update if there was an error.

File: pkg/dns/util/util.go [hunk 9]
```diff
@@ -87,3 +89,37 @@ func HashServiceRecord(msg *msg.Service) string {
 	h.Write([]byte(s))
 	return fmt.Sprintf("%x", h.Sum32())
 }
+
+func ValidateHostAndPort(hostAndPort string) error {
```
Comment (bowei) [inline pkg/dns/util/util.go]: Move unit tests as well. Are there any unit tests?

File: pkg/e2e/options.go [hunk 10]
```diff
@@ -17,8 +17,9 @@ limitations under the License.
 package e2e
 
 const (
-	etcdImage      = "quay.io/coreos/etcd:v3.0.14"
-	hyperkubeImage = "k8s.gcr.io/hyperkube:v1.5.1"
+	etcdImage       = "quay.io/coreos/etcd:v3.0.14"
+	hyperkubeImage  = "k8s.gcr.io/hyperkube:v1.5.1"
+	dnsmasqPtrImage = "gcr.io/kubernetes-e2e-test-images/dnsmasq-ptr:1.0"
```
Comment (bowei) [inline pkg/e2e/options.go]: what is this?

File: test/e2e/kubedns/kubedns.go [hunk 11]
```diff
@@ -55,4 +59,69 @@ var _ = Describe("kube-dns", func() {
 			kubeDNS.Stop()
 		})
 	})
+
+	It("should forward missed ptr lookup to upstream server", func() {
```
Comment (bowei) [inline test/e2e/kubedns/kubedns.go]: should forward PTR queries to the upstream server

File: test/e2e/kubedns/kubedns.go [hunk 12]
```diff
@@ -55,4 +59,69 @@ var _ = Describe("kube-dns", func() {
...
+		dnsmasq := fr.Docker.Run(
+			"-d",
+			"-p=10054:53/tcp",
+			"-p=10054:53/udp",
+			"--cap-add=NET_ADMIN",
+			fr.Options.DnsmasqPtrImage)
+
+		kubeDNS.Start("kube-dns-ptrfwd", "-v=4", "--config-dir="+configDir)
+
+		By("Get answer without upstream server")
```
Comment (bowei) [inline test/e2e/kubedns/kubedns.go]: getting

File: test/e2e/kubedns/kubedns.go [hunk 13]
```diff
@@ -55,4 +59,69 @@ var _ = Describe("kube-dns", func() {
...
+
+		if _, err := os.Stat(configDir); err == nil {
+			os.RemoveAll(configDir)
+		}
+	})
 })
+
+func doPtrQuery(kubeDNS *e2edns.KubeDNS) error {
+	time.Sleep(1 * time.Second)
+	names, err := kubeDNS.Query("4.3.2.1.in-addr.arpa.", dns.TypePTR)
```
Comment (bowei) [inline test/e2e/kubedns/kubedns.go]: You can use an IP from the testbed range to guarantee no one will reply. `1.2.3.4` may be someone's address.

192.0.2.0/24

https://en.wikipedia.org/wiki/Reserved_IP_addresses

Comment (grayluck) [reply test/e2e/kubedns/kubedns.go]: IP changed. Now using numb upstream server when test starts and then switch to a upstream server with the desired PTR record.

File: test/e2e/kubedns/kubedns.go (hunk 12 above)
Comment (grayluck) [reply test/e2e/kubedns/kubedns.go]: Fixed.

File: test/e2e/kubedns/kubedns.go (hunk 11 above)
Comment (grayluck) [reply test/e2e/kubedns/kubedns.go]: Done.

File: pkg/e2e/options.go (hunk 10 above)
Comment (grayluck) [reply pkg/e2e/options.go]: Now using k8s.gcr.io/k8s-dns-dnsmasq-amd64:1.14.5 instead.

File: pkg/dns/dns.go (hunk 7 above)
Comment (grayluck) [reply pkg/dns/dns.go]: Done.

File: pkg/dns/dns.go (hunk 6 above)
Comment (grayluck) [reply pkg/dns/dns.go]: Done.

File: pkg/dns/dns.go (hunk 5 above)
Comment (grayluck) [reply pkg/dns/dns.go]: Done.

File: pkg/dns/dns.go (hunk 4 above)
Comment (grayluck) [reply pkg/dns/dns.go]: Done.

File: Makefile (hunk 2 above)
Comment (grayluck) [reply Makefile]: Reverted.

File: Makefile (hunk 1 above)
Comment (grayluck) [reply Makefile]: Reverted.

File: cmd/kube-dns/app/server.go (hunk 3 above)
Comment (grayluck) [reply cmd/kube-dns/app/server.go]: It's now in config package.
I am making it public for now in testing purpose. Will change it to private method very soon on Monday.

Comment (grayluck) [reply cmd/kube-dns/app/server.go]: Two validation logic merged. Now skydns's nameserver is synced/guarded by kubedns.

File: pkg/dns/dns.go [hunk 14]
```diff
@@ -135,6 +139,30 @@ func NewKubeDNS(client clientset.Interface, clusterDomain string, timeout time.D
...
 }
 
+func (kd *KubeDNS) updateConfig(nextConfig *config.Config) {
+	kd.configLock.Lock()
+	defer kd.configLock.Unlock()
+	kd.config = nextConfig
+
+	if kd.SkyDNSConfig != nil {
+		var nameServers []string
+		for _, nameServer := range kd.config.UpstreamNameservers {
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/dns/dns.go]: config.go only validates the address of nameservers. Here a default port is appended to the address if the address doesn't have a port.

File: pkg/dns/config/config.go [hunk 15]
```diff
@@ -117,19 +118,21 @@ func (config *Config) validateUpstreamNameserver() error {
...
 		}
-		if len(validation.IsValidIP(nsStrings[0])) > 0 {
-			return fmt.Errorf("invalid nameserver: %q", ns)
+
+		host, port, err := net.SplitHostPort(nameServer)
+		if err != nil {
+			return err
+		}
+		if ip := net.ParseIP(host); ip == nil {
+			return fmt.Errorf("bad IP address: %s", host)
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/dns/config/config.go]: Done.

File: pkg/dns/config/config.go [hunk 16]
```diff
@@ -117,19 +118,21 @@ func (config *Config) validateUpstreamNameserver() error {
...
+		}
+		if p, _ := strconv.Atoi(port); p < 1 || p > 65535 {
+			return fmt.Errorf("bad port number %s", port)
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/dns/config/config.go]: Done.

File: test/e2e/kubedns/kubedns.go [hunk 17]
```diff
@@ -55,4 +59,96 @@ var _ = Describe("kube-dns", func() {
...
+		}
+		defer func() {
+			if _, err := os.Stat(workDir); err == nil {
+				os.RemoveAll(workDir)
+			}
+		}()
+
+		configDir := workDir + "/kube-dns-config"
+		if err := os.MkdirAll(configDir, 0744); err != nil {
+			panic(err)
```
Comment (bowei) [inline test/e2e/kubedns/kubedns.go]: Expect("foo").To(Equal("foo"))

Comment (grayluck) [reply test/e2e/kubedns/kubedns.go]: Done.

File: cmd/kube-dns/app/server.go [hunk 18]
```diff
@@ -163,55 +160,12 @@ func setupSignalHandlers() {
...
-	return nameServer, err
-}
-
 func (d *KubeDNSServer) startSkyDNSServer() {
 	glog.V(0).Infof("Starting SkyDNS server (%v:%v)", d.dnsBindAddress, d.dnsPort)
 	skydnsConfig := &server.Config{
 		Domain:  d.domain,
 		DnsAddr: fmt.Sprintf("%s:%d", d.dnsBindAddress, d.dnsPort),
 	}
-	if d.nameServers != "" {
```
[the remark this answers is not in the document]
Comment (grayluck) [reply cmd/kube-dns/app/server.go]: It will get initialized when kubeDNS initialize its configuration through Once.
Let's say the user provides nameservers as commandline parameters. In the case of using configMap or configDir, the nameserver from command line will be overwriten when kubedns initializes its config through sync once. As for no configmap or configdir, both kubedns and skydns will use the nameserver from commandline parameter after kubedns sync once. 
https://github.com/grayluck/dns/blob/0aaf6028e388502bf6c7948d0cdd02047c55daaa/cmd/kube-dns/app/server.go#L73

File: pkg/dns/util/util.go [hunk 19]
```diff
@@ -87,3 +89,23 @@ func HashServiceRecord(msg *msg.Service) string {
...
+	if ip := net.ParseIP(nameServer); ip != nil {
+		return ip.String(), "53", nil
+	}
+
+	host, port, err := net.SplitHostPort(nameServer)
+	if err != nil {
+		return "", "", err
+	}
+	if ip := net.ParseIP(host); ip == nil {
+		return "", "", fmt.Errorf("bad IP address: %s", host)
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/dns/util/util.go]: Fixed.

File: pkg/dns/util/util.go [hunk 20]
```diff
@@ -87,3 +89,23 @@ func HashServiceRecord(msg *msg.Service) string {
...
+	}
+	if p, _ := strconv.Atoi(port); p < 1 || p > 65535 {
+		return "", "", fmt.Errorf("bad port number %s", port)
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/dns/util/util.go]: Fixed.

File: pkg/dns/util/util_test.go [hunk 21]
```diff
@@ -0,0 +1,49 @@
...
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package util
+
+import (
+	"testing"
+
+	"github.com/stretchr/testify/assert"
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/dns/util/util_test.go]: Done.

File: pkg/dns/util/util_test.go [hunk 22]
```diff
@@ -0,0 +1,49 @@
...
+		{false, "", "", ""},
+		{true, "1.2.3.4", "1.2.3.4", "53"},
+		{true, "1.2.3.4:53", "1.2.3.4", "53"},
+		{false, "1.1.1.1:abc", "", ""},
+		{false, "1.1.1.1:123456789", "", ""},
+		{false, "1.1.1.1:", "", ""},
+		{false, "asdf", "", ""},
+	} {
+		ip, port, err := ValidateNameserverIpAndPort(tc.nameserver)
+		if tc.isValid {
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/dns/util/util_test.go]: Changed.

File: pkg/dns/util/util_test.go [hunk 23]
```diff
@@ -0,0 +1,49 @@
...
+			assert.NoError(t, err, "%s should be valid nameserver", tc.nameserver)
+		} else {
+			assert.Error(t, err, "%s should not be valid nameserver", tc.nameserver)
+		}
+		assert.Equal(t, tc.expectedIp, ip, "Ip doesn't match.")
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/dns/util/util_test.go]: Done.

File: pkg/dns/util/util_test.go [hunk 24]
```diff
@@ -0,0 +1,49 @@
...
+
+import (
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+)
+
+func TestValidateNameserverIpAndPort(t *testing.T) {
+	for _, tc := range []struct {
+		isValid      bool
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/dns/util/util_test.go]: Done.

File: pkg/dns/util/util_test.go [hunk 25]
```diff
@@ -0,0 +1,49 @@
...
+		nameserver   string
+		expectedIp   string
+		expectedPort string
+	}{
+		{false, "", "", ""},
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/dns/util/util_test.go]: Done.

File: pkg/dns/util/util_test.go [hunk 26]
```diff
@@ -0,0 +1,49 @@
...
+		{true, "1.2.3.4", "1.2.3.4", "53"},
+		{true, "1.2.3.4:53", "1.2.3.4", "53"},
+		{false, "1.1.1.1:abc", "", ""},
+		{false, "1.1.1.1:123456789", "", ""},
+		{false, "1.1.1.1:", "", ""},
+		{false, "asdf", "", ""},
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/dns/util/util_test.go]: Added.

File: pkg/e2e/dns/dns.go [hunk 27]
```diff
@@ -31,12 +31,15 @@ import (
...
 // KubeDNS daemon
 type KubeDNS struct {
+	name      string
 	cmd       *exec.Cmd
 	isRunning bool
 }
 
 // Start kube DNS, passing in extra arguments
-func (kd *KubeDNS) Start(args ...string) {
+func (kd *KubeDNS) Start(name string, args ...string) {
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/e2e/dns/dns.go]: Doc updated.

File: pkg/dns/util/util_test.go [hunk 28]
```diff
@@ -0,0 +1,49 @@
+/*
+Copyright 2016 The Kubernetes Authors.
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/dns/util/util_test.go]: Fixed.

File: pkg/dns/dns.go [hunk 29]
```diff
@@ -135,6 +139,27 @@ func NewKubeDNS(client clientset.Interface, clusterDomain string, timeout time.D
...
+				return
+			} else {
+				nameServers = append(nameServers, net.JoinHostPort(ip, port))
+			}
+		}
+		kd.SkyDNSConfig.Nameservers = nameServers
+	}
+	kd.config = nextConfig
+	glog.V(2).Infof("Configuration updated: %+v", *kd.config)
+
```
[the remark this answers is not in the document]
Comment (grayluck) [reply pkg/dns/dns.go]: Fixed.

**Comment by bowei** [comment]
Ok, can you squash all of the commits and clean up the commit message?

`git rebase -i upstream/master`

then we can merge.

**Comment by grayluck** [comment]
Squashed. Also changed the title of this PR.
